plugin 'cocoapods-publish'

# 开启二进制模式
baitu_use_frameworks!

use_frameworks!

platform :ios, '11.4'

target 'JPVideoPlayer_Example' do
  pod 'JPVideoPlayer', :path => '../', :dev => 1

  target 'JPVideoPlayer_Tests' do
    inherit! :search_paths

    
  end
end
